# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08c660892fec61d2d7d87b8ad4e133251f22dbea3756a50d873ff34435e64f775e56810e5ca459eca683f228e4a1da2bcbd83fd9a3ce901dc772be8c7a4ad087

test:
  secret_key_base: dd8acbc83a05bea34bf493c259d3fb7bbf1e3990a7785c6cb30f6a9ef708a5d848e5dab8111fe84bd9fa4c68ca3248793e009d5f3b8092d5b058f310cd4cfb71

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
